#!/usr/bin/env bash

. ../support/run-support.sh

cmd_fn() {
  d="${1}"
  p="${2}"

  echo "go run main.go ${d} ${p}"
}

inputs_dir_fn() {
  d="${1}"
  p="${2}"

  day=$(printf "%02d" $d)
  echo "internal/day${day}/inputs"
}

run "cmd_fn" "inputs_dir_fn"
